server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tp-7
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: false
    ddl-auto: validate

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true

jwt:
  secret: YOUR_SECRET_KEY
  expiration: 86400000

logging:
  level:
    ru.bmstu: DEBUG

springdoc:
  swagger-ui:
    url: /v2/api-docs
    path: /swagger-ui.html